# conda_env.yml
# Configuration file for creating a Conda Environment with dependencies needed for GSSHApy.
# Create the environment by running the following command (after installing Miniconda):
# os: linux
#   $ conda env create -f conda_env.yml

name: gssha
channels:
- conda-forge
- defaults
dependencies:
- python=2
- affine
- appdirs
- mapkit
- psycopg2
# pynio does not work on Windows
#- pynio
- pyyaml
- rapidpy
- timezonefinder
- utm
- wrf-python
